[component]
structures = []
label = "Button"
description = ""
icon = "crop_7_5"
tags = []

[props]
label = "Button"
type.select = ["Primary", "Secondary"]
link_url = "/"
open_in_new_tab = false

[props.width]
type.select = ["Small", "Large"]