[component]
structures = []
label = "Project Card"
description = "Project card used for project lists"
icon = "wysiwyg"
tags = []

[props.project]
title = "Hello World"
subtitle = "Lorem Ipsum"
image = "https://placekitten.com/800/400"
url = "/"